### ISSUE TITLE
Build error with latest version of Babel

### ISSUE THREAD

**Issue by ReidBraswell** [mAAdhaTTah/babel-plugin-prismjs#8] opened 2019-05-28 16:56 UTC
Below is the error I received with:
- `@babel/core` - `v7.4.5`
- `prismjs` - `v1.16.0`
- `babel-plugin-prismjs` - `v1.0.2`

```
Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: Cannot read property 'require' of undefined
    at getRequire (C:\repo\node_modules\babel-plugin-prismjs\lib\getComponents.js:25:42)
    at C:\repo\node_modules\babel-plugin-prismjs\lib\getComponents.js:53:36
    at Array.reduce (<anonymous>)
    at getDependencies (C:\repo\node_modules\babel-plugin-prismjs\lib\getComponents.js:52:20)
    at Array.reduce (<anonymous>)
    at _default (C:\repo\node_modules\babel-plugin-prismjs\lib\getComponents.js:81:39)
    at PluginPass.ImportDeclaration (C:\repo\node_modules\babel-plugin-prismjs\lib\index.js:27:53)
    at newFn (C:\repo\node_modules\@babel\traverse\lib\visitors.js:193:21)
```

**Comment by mAAdhaTTah** [comment] 2019-05-28 17:31
Could you share your babel configuration?

**Comment by ReidBraswell** [comment] 2019-05-28 18:02
Sure!

`babel.config.js`

```js
module.exports = {
    presets: [
        [
            '@babel/preset-env',
            {
                useBuiltIns: 'entry',
                corejs: 3,
                modules: false,
                exclude: ['transform-typeof-symbol'],
            },
        ],
    ],
};
```

**Comment by mAAdhaTTah** [comment] 2019-05-28 18:30
Are you sure that's the right config? The `prismjs` plugin isn't there.

**Comment by ReidBraswell** [comment] 2019-05-28 18:50
Sorry I had taken it out before I moved on. I had essentially the default config for the `prismjs` plugin in the `plugins` array.

**Comment by mAAdhaTTah** [comment] 2019-05-28 19:16
Yeah, the configuration is likely to be the cause of the issue. My guess is this is a dupe of #4, and we really need to add #1 as we;; to help with these issues. If those don't solve your issues, feel free to reopen.

**Closed by mAAdhaTTah** 2019-05-28 19:16 UTC
