### ISSUE TITLE
'lang-pug' data-dependencies is not working

### ISSUE THREAD

**Issue by pronist** [mAAdhaTTah/babel-plugin-prismjs#6] opened 2019-02-02 20:56 UTC
Using **nuxt.js 2.4.2**, I added babel-plugin-prismjs in **nuxt.config.js**

```javascript
"plugins": [
  ["prismjs", {
      "languages": ["pug", "javascript", "css", "stylus", "markup"],
      "plugins": ["autoloader", "toolbar", "copy-to-clipboard"],
      "theme": "tomorrow",
      "css": true
  }]
]
```

in **.vue**

```vue
<template lang="pug">
    pre(data-label="HelloWorld.pug" data-dependencies="css")
      code.lang-pug {{ index }}
</template>

<script>
import Prism from 'prismjs';

export default {
  data() {
    return {
      index: `//- CSS is not highlight
style.
  body {
    margin: 0px;
    padding: 0px;
  }
h1 Hello, World!
script.
  console.log("Hello, World!");`
    }
  }
}
</script>
```

**Comment by pronist** [comment] 2019-02-06 21:31
in **prism-autoloader.js**

```javascript
  var languages_path = 'components/';
  if(script.hasAttribute('data-autoloader-path')) {
    var path = script.getAttribute('data-autoloader-path').trim();
    if(path.length > 0 && !/^[a-z]+:\/\//i.test(script.src)) {
      languages_path = path.replace(/\/?$/, '/');
    }
  } else if (/[\w-]+\.js$/.test(script.src)) {
    languages_path = script.src.replace(/[\w-]+\.js$/, 'components/');
  }
  var config = Prism.plugins.autoloader = {
    languages_path: languages_path,
    use_minified: true
  };

  /** http://localhost:3000/_nuxt/components/ */
  console.log(languages_path);
```

When using webpack, **prismjs** components are in **node_modules/prismjs/components**,
but **autoloader** is not 'require', or 'import' the folder :(

**Comment by mAAdhaTTah** [comment] 2019-02-06 21:34
You don't need the autoloader if you're already compiling the language definitions. You also want `pug` to be last in the list. That should be solved internally though.

**Comment by mAAdhaTTah** [comment] 2019-07-18 16:53
Closing as duplicate of #4.

**Closed by mAAdhaTTah** 2019-07-18 16:53 UTC
